Repository milieuinfo/webcomponent-vl-ui-icon, pull requests merged in 2019-09, with the labels that each got.

#19 UIG-218
  vl-icon.src.js
Labels: maintenance

#20 Update link naar demo
  vl-icon.src.js
Labels: maintenance

#21 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#25 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#24 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#23 Update dependency @govflanders/vl-ui-util to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#22 Update dependency @govflanders/vl-ui-icon to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#10 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#26 Revert naar @govflanders 3.7.2
  package-lock.json
  package.json
Labels: bug

#32 Automatic commit via update script
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  style.css
  style.css.map
Labels: maintenance

#34 Update and install latest util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
Labels: maintenance

#36 Update vl-ui-util
  CODEOWNERS
  package-lock.json
  package.json
Labels: maintenance
