Repository milieuinfo/webcomponent-vl-ui-icon, pull requests merged in 2020-06, with the labels that each got.

#76 Introductie vl-ui-demo en ESlint
  .eslintrc.json
  CODEOWNERS
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  demo/vl-icon.html
  index.js
  package-lock.json
  package.json
  src/index.js
  src/vl-icon.js
  test/e2e/components/vl-icon.js
  test/e2e/icon.test.js
  test/e2e/pages/vl-icon.page.js
  test/unit/vl-icon.test.html
Labels: chore

#77 Importeer sinon vanuit node_modules voor de unit testen
  package-lock.json
  src/style.css
  src/style.css.map
Labels: bugfix

#81 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
  src/style.css
Labels: enhancement

#82 Update vl-ui-core en vl-ui-util dependency
  package-lock.json
  package.json
Labels: chore

#84 Deduplicatie NPM run scripts Update naar latest vl-ui-util en vl-ui-core
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore
